-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 15:53:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;




-- -----------------------------------------------------
-- Table `blog`.`statut_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`statut_utilisateur` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `statut_utilisateur` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `statut_utilisateur_id_status` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`, `statut_utilisateur_id_status`),
  INDEX `fk_utilisateur_statut_utilisateur1_idx` (`statut_utilisateur_id_status` ASC),
  CONSTRAINT `fk_utilisateur_statut_utilisateur1`
    FOREIGN KEY (`statut_utilisateur_id_status`)
    REFERENCES `blog`.`statut_utilisateur` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `chapo` VARCHAR(45) NULL,
  `descriptif` VARCHAR(255) NULL,
  `auteur` VARCHAR(45) NULL,
  `date_creation` DATETIME NULL,
  `date_maj` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`commentaire` (
  `id_commentaire` INT NOT NULL AUTO_INCREMENT,
  `post_id_post` INT NOT NULL,
  PRIMARY KEY (`id_commentaire`, `post_id_post`),
  INDEX `fk_commentaire_post1_idx` (`post_id_post` ASC) ,
  CONSTRAINT `fk_commentaire_post1`
    FOREIGN KEY (`post_id_post`)
    REFERENCES `blog`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`statut_commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`statut_commentaire` (
  `id_statut_commentaire` INT NOT NULL AUTO_INCREMENT,
  `statut_commentaire` VARCHAR(45) NULL,
  `commentaire_id_commentaire` INT NOT NULL,
  `commentaire_post_id_post` INT NOT NULL,
  PRIMARY KEY (`id_statut_commentaire`, `commentaire_id_commentaire`, `commentaire_post_id_post`),
  INDEX `fk_statut_commentaire_commentaire1_idx` (`commentaire_id_commentaire` ASC, `commentaire_post_id_post` ASC),
  CONSTRAINT `fk_statut_commentaire_commentaire1`
    FOREIGN KEY (`commentaire_id_commentaire` , `commentaire_post_id_post`)
    REFERENCES `blog`.`commentaire` (`id_commentaire` , `post_id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
